import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Footer from '../components/Footer';
import styles from '../styles/Hero.module.scss';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={`container`}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <title>CAES</title>
      </Head>
      <Header />

      <main class={`hero`}>
        <div class={`overlay`}>
          <div class={`title-group`}>
            <h2 class={`title`}>Vota na chapa</h2>
            <h3 class={`subtitle`}>
              Nós somos a chapa mais quente que você já viu
            </h3>
          </div>
          <div class={`button-group`}>
            <button class={`button-prop`}>
              <Link href='/propostas'>PROPOSTAS</Link>
            </button>
            <button class={`button-sbn`}>
              <Link href='/sobreNos'>Sobre nós</Link>
            </button>
          </div>
        </div>
        <div class={`image rocket`}>
          <img class={`rocket`} src={`rocket.png`} />
        </div>
      </main>

      <article class={`art-1`}>
        <img class={`art-img`} src={`defaultRect.png`} />
        <div class={`text-group`}>
          <h2 class={`art-title`}>O que é o CAWS</h2>
          <p class={`art-text`}>
            Texto informativo sobre o que é o CAWS e sua importância. Um texto
            grande o suficiente para chegar até o pé da imagem, no máximo. Ou
            para ficar centralizado bonitinho. Foto do CAWS ou do campus? Texto
            informativo sobre o que é o CAWS e sua importância. Um texto grande
            o suficiente para chegar até o pé da imagem, no máximo. Ou para
            ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
            informativo sobre o que é o CAWS e sua importância. Um texto grande
            o suficiente para chegar até o pé da imagem, no máximo. Ou para
            ficar centralizado bonitinho. Foto do CAWS ou do campus?
          </p>
        </div>
      </article>

      <article class={`art-2`}>
        <div class={`text-group`}>
          <h2 class={`art-title`}>Eleições</h2>
          <p class={`art-text`}>
            Texto informativo sobre o que é o CAWS e sua importância. Um texto
            grande o suficiente para chegar até o pé da imagem, no máximo. Ou
            para ficar centralizado bonitinho. Foto do CAWS ou do campus? Texto
            informativo sobre o que é o CAWS e sua importância. Um texto grande
            o suficiente para chegar até o pé da imagem, no máximo. Ou para
            ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
            informativo sobre o que é o CAWS e sua importância. Um texto grande
            o suficiente para chegar até o pé da imagem, no máximo. Ou para
            ficar centralizado bonitinho. Foto do CAWS ou do campus?
          </p>
        </div>
        <img class={`art-img`} src={`defaultRect.png`} />
      </article>

      <Footer />
    </div>
  );
}
