import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import Footer from '../components/Footer';
import styles from '../styles/Hero.module.scss';
import Link from 'next/link';

export default function SobreNos() {
  return (
    <div className={`container`}>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'
        ></meta>
        <link rel='icon' href='/favicon.ico' />
        <title>CAES</title>
      </Head>
      <Header />

      <main class={`hero-sbn`}>
        <div class={`overlay`}>
          <div class={`title-group`}>
            <h2 class={`title`}>A CAES</h2>
            <h3 class={`subtitle`}>Chapa Acadêmica Ester Sabino</h3>
          </div>
          <div class={`button-group`}>
            <button class={`button-prop`}>
              <Link href='/propostas'>
                <a class={`prop-link`}>PROPOSTAS</a>
              </Link>
            </button>
            <button class={`button-sbn`}>
              <Link href='/sobreNos'>
                <a class={`sbn-link`}>Sobre nós</a>
              </Link>
            </button>
          </div>
        </div>
        <div class={`image`}></div>
      </main>

      <div class={`art-sbn-group`}>
        <article class={`art-1`}>
          <div class={`art-img chapa`}></div>
          <div class={`text-group`}>
            <h2 class={`art-title`}>A Chapa</h2>
            <h3 class={`art-subtitle`}>Nossos valores</h3>
            <p class={`art-text`}>
              A <span class={`bold`}>Chapa Acadêmica Ester Sabino</span> surge
              como a união de estudantes que desejam realizar o melhor possível
              pelo curso de Física. Priorizamos a escolha de um nome feminino
              por representatividade, já que até o momentos só tivemos nomes
              masculinos. O nome Ester Sabino foi escolhido como homenagem a
              brasileira professora/pesquisadora/médica que sequenciou o covid
              em dois dias. Entre as nossas prioridades, enquanto chapa,
              destacamos o nosso desejo imenso de estabelecer com os estudantes
              e colegas um contato de forma mais abrangente, próxima e íntima. É
              nosso desejo também, que esse contato perpasse a esfera
              estudante-estudante e se estenda a esfera estudante-professor.
              Entedemos como primordial para um bom processo de
              ensino-aprendizagem que os docentes e discentes estejam unidos e
              engajados em um só objetivo. Infelizmente a pandemia acobou por
              nos separar físicamente e, com isso, perdemos o calor humano e as
              relações interpessoais e afetivas que são construidas e
              consolidadas no dia a dia em sala de aula. Tendo em mente esse
              fato, trabalharemos para que ocorram momentos de aproximação,
              vitual por hora, para que mesmo que estejamos distantes, estejamos
              proximos. Assim ninguém se sente sozinho e um ajuda ao outro.
            </p>
          </div>
        </article>

        <article class={`art-2`}>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Natasha Oliveira</h2>
            <h3 class={`art-subtitle`}>Presidente</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
          <div class={`art-img natasha`}></div>
        </article>
      </div>

      <div class={`art-sbn-group`}>
        <article class={`art-1`}>
          <div class={`art-img arthur`}></div>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Arthur</h2>
            <h3 class={`art-subtitle`}>Vice presidente</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
        </article>

        <article class={`art-2`}>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Gabriel Galeano</h2>
            <h3 class={`art-subtitle`}>Diretor de Comunicação</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
          <div class={`art-img galeano`}></div>
        </article>
      </div>

      <div class={`art-sbn-group`}>
        <article class={`art-1`}>
          <div class={`art-img mauricio`}></div>
          <div class={`text-group mau`}>
            <h2 class={`art-title`}>Maurício Matos</h2>
            <h3 class={`art-subtitle`}>
              1º Secretário de Comunicação e Representante do Bacharelado
            </h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
        </article>

        <article class={`art-2`}>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Felipe Penha</h2>
            <h3 class={`art-subtitle`}>2º Secretário de Comunicação</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>

          <div class={`art-img felipe`}></div>
        </article>
      </div>

      <div class={`art-sbn-group`}>
        <article class={`art-1`}>
          <div class={`art-img patrick`}></div>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Patrick Cardoso</h2>
            <h3 class={`art-subtitle`}>Secretário Geral</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
        </article>

        <article class={`art-2`}>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Maria Alice</h2>
            <h3 class={`art-subtitle`}>Vice da Secretaria Geral</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
          <div class={`art-img alice`}></div>
        </article>
      </div>

      <div class={`art-sbn-group`}>
        <article class={`art-1`}>
          <div class={`art-img ivo`}></div>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Ivo Amorim</h2>
            <h3 class={`art-subtitle`}>Tesoureiro</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
        </article>

        <article class={`art-2`}>
          <div class={`text-group`}>
            <h2 class={`art-title`}>Julya Vieira</h2>
            <h3 class={`art-subtitle`}>Vice da Tesouraria</h3>
            <p class={`art-text`}>
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
              Texto informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?Texto
              informativo sobre o que é o CAWS e sua importância. Um texto
              grande o suficiente para chegar até o pé da imagem, no máximo. Ou
              para ficar centralizado bonitinho. Foto do CAWS ou do campus?
            </p>
          </div>
          <div class={`art-img julya`}></div>
        </article>
      </div>

      <Footer />
    </div>
  );
}
